In [9]:
import pandas as pd
import glob

files = glob.glob(f"/Users/euanbronsky/Downloads/Options.SPX.20*/*.txt")

# Files are now stored in a list of strings, so we can directly loop over it

In [10]:
df = pd.concat([pd.read_csv(f, sep = ',', engine='c', low_memory=False) for f in files], ignore_index=True)

# ignore_index=True makes a continuous index after concatenating rather than starting the index over for each file

# sep = ',' tells pandas that the columns in the file are separated by commas

# SPX.20* matches any folder that starts with SPX.20, i.e. SPX.2011 SPX 2012

# *.txt matches any file name that ends in .txt

# glob finds files whose names match a pattern, this is what allows to use * to match pattern

# glob.glob: module is glob function is glob()

# using engine = 'c' helps load the data faster

# low_memory = False ignores warning, and reads the whole file at once

In [11]:
df.columns = df.columns.str.replace(r'[\[\]]', '', regex=True).str.lower().str.strip()

# regex = regular expression , using this you can describe patterns instead of exact text
# r' ensures python interprets \ as an actual string and not a special character
# outer [] defines character class, we match any character inside []
# regex needs to be told the inner [] are not character classes, and that is what the backslash does, it says that it is not a character class but a string we wasnt to remove
# r'[\[\],!?&] removes [] , ! ? &

In [13]:
relevant_cols = ['quote_date', 'underlying_last', 'expire_date','dte','strike','c_iv','p_iv','c_bid', 'c_ask', 'p_bid', 'p_ask']

df2 = df[relevant_cols]
df2['quote_date'] = pd.to_datetime(df2['quote_date'])

In [31]:
df2[df2['dte'] >= 360]

,quote_date,underlying_last,expire_date,dte,strike,c_iv,p_iv,c_bid,c_ask,p_bid,p_ask
8293169,2011-01-03,1271.36,2011-12-30,361.0,600.0,,0.395560,649.9,655.89,3.5,4.8
8293170,2011-01-03,1271.36,2011-12-30,361.0,700.0,,0.361400,553.9,559.89,6.8,8.5
8293171,2011-01-03,1271.36,2011-12-30,361.0,800.0,,0.331980,460.09,466.1,11.6,15.5
8293172,2011-01-03,1271.36,2011-12-30,361.0,900.0,0.260960,0.303270,369.5,375.51,20.61,24.41
8293173,2011-01-03,1271.36,2011-12-30,361.0,950.0,0.267100,0.289210,325.9,331.9,26.8,30.79
...,...,...,...,...,...,...,...,...,...,...,...
698011,2023-12-29,4772.17,2029-12-21,2184.0,7200.0,0.174010,,286.8,366.8,1550.9,1630.9
698012,2023-12-29,4772.17,2029-12-21,2184.0,7400.0,0.170630,,245.4,325.4,1669.0,1749.0
698013,2023-12-29,4772.17,2029-12-21,2184.0,7600.0,0.166880,,208.7,288.7,1791.8,1871.8
698014,2023-12-29,4772.17,2029-12-21,2184.0,7800.0,0.163950,,176.3,256.3,1820.0,2124.7
698015,2023-12-29,4772.17,2029-12-21,2184.0,8000.0,0.161640,,147.9,227.9,2054.1,2134.1

In [15]:
df2.sort_values(by=['quote_date', 'expire_date', 'strike'], inplace=True)

# inplace=True sorts existing dataframe and saves the result directly in df2, so no reassignment like df2 = df2 is needed

In [18]:
df2.tail()

,quote_date,underlying_last,expire_date,dte,strike,c_iv,p_iv,c_bid,c_ask,p_bid,p_ask
698011,2023-12-29,4772.17,2029-12-21,2184.0,7200.0,0.174010,,286.8,366.8,1550.9,1630.9
698012,2023-12-29,4772.17,2029-12-21,2184.0,7400.0,0.170630,,245.4,325.4,1669.0,1749.0
698013,2023-12-29,4772.17,2029-12-21,2184.0,7600.0,0.166880,,208.7,288.7,1791.8,1871.8
698014,2023-12-29,4772.17,2029-12-21,2184.0,7800.0,0.163950,,176.3,256.3,1820.0,2124.7
698015,2023-12-29,4772.17,2029-12-21,2184.0,8000.0,0.161640,,147.9,227.9,2054.1,2134.1

In [35]:
df2.sort_values(by=['quote_date', 'expire_date','strike'])

,quote_date,underlying_last,expire_date,dte,strike,c_iv,p_iv,c_bid,c_ask,p_bid,p_ask
8292376,2011-01-03,1271.36,2011-01-07,4.0,1050.0,,0.533330,219.6,221.11,0.0,0.05
8292377,2011-01-03,1271.36,2011-01-07,4.0,1075.0,,0.471210,194.61,196.1,0.0,0.05
8292378,2011-01-03,1271.36,2011-01-07,4.0,1100.0,,0.411160,169.6,171.1,0.0,0.05
8292379,2011-01-03,1271.36,2011-01-07,4.0,1125.0,,0.391020,144.6,146.1,0.04,0.11
8292380,2011-01-03,1271.36,2011-01-07,4.0,1150.0,,0.345100,119.6,121.2,0.1,0.16
...,...,...,...,...,...,...,...,...,...,...,...
698011,2023-12-29,4772.17,2029-12-21,2184.0,7200.0,0.174010,,286.8,366.8,1550.9,1630.9
698012,2023-12-29,4772.17,2029-12-21,2184.0,7400.0,0.170630,,245.4,325.4,1669.0,1749.0
698013,2023-12-29,4772.17,2029-12-21,2184.0,7600.0,0.166880,,208.7,288.7,1791.8,1871.8
698014,2023-12-29,4772.17,2029-12-21,2184.0,7800.0,0.163950,,176.3,256.3,1820.0,2124.7
698015,2023-12-29,4772.17,2029-12-21,2184.0,8000.0,0.161640,,147.9,227.9,2054.1,2134.1

In [38]:
pd.to_numeric(df2['c_bid'])
df2[df2['c_bid'] >= 500]

ValueError: Unable to parse string " " at position 43489

In [50]:
df2.iloc[43488]

quote_date         2011-03-14 00:00:00
underlying_last                1296.42
expire_date                 2011-06-16
dte                               94.0
strike                           975.0
c_iv
p_iv                          0.331880
c_bid                       318.600000
c_ask                       321.300000
p_bid                         3.400000
p_ask                         4.310000
Name: 8259776, dtype: object